# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1362564153);
user_pref("app.update.lastUpdateTime.background-update-timer", 1350034535);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1350034415);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1350368805);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1350368925);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.migration.version", 6);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.buildID", "20121010144125");
user_pref("browser.startup.homepage_override.mstone", "16.0.1");
user_pref("browser.syncPromoViewsLeft", 4);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 13);
user_pref("extensions.enabledAddons", "autoauth@efinke.com:2.1,{972ce4c6-7e08-4474-a285-3208198ce6fd}:16.0.1");
user_pref("extensions.hotfix.certs.1.sha1Fingerprint", "CA:C4:7D:BF:63:4D:24:E9:DC:93:07:2F:E3:C8:EA:6D:C3:94:6E:89");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/Applications/Firefox.app/Contents/MacOS/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1350362426000}}},{\"name\":\"app-profile\",\"addons\":{\"autoauth@efinke.com\":{\"descriptor\":\"/Users/csliu/Library/Application Support/Firefox/Profiles/p3pf34d7.QAAutomation/extensions/autoauth@efinke.com.xpi\",\"mtime\":1350032583000}}}]");
user_pref("extensions.lastAppVersion", "16.0.1");
user_pref("extensions.lastPlatformVersion", "16.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.layers.direct3d9", 3);
user_pref("idle.lastDailyNotification", 1349950798);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1362564032);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1365156042);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
