# Pages
require 'phoenix_site/phoenix_site'
require 'phoenix_site/pages/select_dom_page'
require 'phoenix_site/pages/registration_page'
require 'phoenix_site/pages/partner_fill_out_page'
require 'phoenix_site/pages/licensing_fill_out_page'
require 'phoenix_site/pages/billing_fill_out_page'
require 'phoenix_site/pages/registration_complete_page'
require 'phoenix_site/pages/account_page'
