$:.unshift(File.dirname(__FILE__))

require 'rubygems'
require 'bundler'
Bundler.setup
require "selenium-webdriver"
require 'rspec'
#require 'nokogiri'
require 'forgery'
require 'csv'
require 'rest_client'
require 'json'
require 'time'
require 'active_support/time'
require 'chronic'
require 'diffy'
require 'net/http'
require 'digest/sha1'
require 'openssl'
require 'erb'
require 'ostruct'

require 'capybara/cucumber'
#require 'capybara-webkit'

require 'aria_api/lib/aria_api'
require 'file_helper'
require 'bill_helper'
require 'db_helper'
require 'ldap_helper'
require 'ssh_helper'
require 'ssh_migration'
require 'utility'
require 'device_helper'
require 'ssh_tds_grow_quota'
require 'testlink_helper'
require 'common_helper'
require 'restore_helper'
require 'client_api_helper'
require 'client_config_helper'
require 'move_enterprise_to_dps'
require 'customcd_api_helper'
require 'site_helper/site_helper'
require 'capybara_helper/capybara_helper'
require 'bifrost_helper/bifrost_helper'
require 'email_helper/email_helper'
require 'system_extension/protocol'

include FileHelper
include DBHelper
include LDAPHelper
include SSHHelper
include SSHMigration
include SSHReap
include SSHTDSGrowQuota
include SSHRecordOverdraft
include SSHPushConnector
include SSHKalypsoE2E
include SSHLinuxE2E
include AriaApi
include Utility
include KeylessDeviceActivation
include Activation
include DataShuttleSeeding
include Email
include Billing
include MachineInfo
include ClientUserResources
include LinuxBackupSets
include MoveEnterpriseToDPS
include CustomCDAPI
