$:.unshift(File.dirname(__FILE__))
require 'elements/select'
require 'elements/table'
require 'elements/text_field'
require 'elements/definition_list'
require 'elements/element'
require 'javascript_helper'
require 'extension/context'
require 'extension/log'
require 'session/session'